### ISSUE TITLE
Error: Cannot read property 'has' of undefined.

### ISSUE THREAD

**Issue by sagunpandey** [EmbeddedEnterprises/ngx-golden-layout-electron#1]
I am getting this error:

`Cannot read property 'has' of undefined.`

The error is coming out from ngx-golden-layout.js -> MultiWindowService() function. For some reason rootWindow.__ServiceConstructors is undefined. I did try creating a MultiWindowService and adding it to the module. What is it that I am doing wrong?

![screenshot](https://user-images.githubusercontent.com/3306020/62874653-a56b7780-bcef-11e9-8502-82510cbf7ed2.png)

**Comment by danemesis** [comment]
@sagunpandey you closed the issue, did you figure out what you did wrong or found workaround? 

upd. never mind. I found your another message here https://github.com/EmbeddedEnterprises/ng6-golden-layout/issues/25. Although it did not help me
